---
# vim: ft=yaml
version: '2'
services:
  jenkins_npm:
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
volumes:
  jenkins_home:
